const amortisation = {
  data: {
    type: 'calculationResult',
    attributes: {
      productCode: 'FRST',
      primaryClientType: 'I',
      settlementDate: '2019-11-11',
      maturityDate: '2020-11-09',
      interestRate: 19,
      balloonAmount: 0,
      residualValue: 0,
      valueOfAdvInstalments: 0,
      netDeposit: 0,
      amountFinanced: 1000,
      interestAmount: 99.8,
      amountPayable: 1099.8,
      gstOnInterest: 0,
      disclosedRate: 19.04,
      trueRate: 19.04,
      gst: 0,
      amountFinancedExclGSTAdvance: 0,
      gstPayablePostAdvance: 0,
      repaymentOptions: {
        weeklyAmount: 4.88,
        numberOfWeeklyPayments: 225,
        firstWeeklyPaymentDate: '2019-11-25',
      },
      paymentFrequency: {
        value: 1,
        unit: 'W',
      },
      costOfGoods: {
        value: 1000,
        overriddenLct: 0,
        overriddenGst: 130.43,
      },
      term: {
        value: 12,
        unit: 'M',
      },
      instalmentBreakdown: {
        total: {
          principal: 1000,
          interest: 99.8,
          nonCapitalisedFees: 0,
          gst: 0,
        },
        instalments: [
          {
            seq: 1,
            gstRecoveryOption: 'None',
            date: '2019-11-18T03:41:11',
            principal: 17.5,
            interest: 3.65,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 2,
            gstRecoveryOption: 'None',
            date: '2019-11-25T03:41:11',
            principal: 17.57,
            interest: 3.58,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 3,
            gstRecoveryOption: 'None',
            date: '2019-12-02T03:41:11',
            principal: 17.63,
            interest: 3.52,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 4,
            gstRecoveryOption: 'None',
            date: '2019-12-09T03:41:11',
            principal: 17.69,
            interest: 3.46,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 5,
            gstRecoveryOption: 'None',
            date: '2019-12-16T03:41:11',
            principal: 17.76,
            interest: 3.39,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 6,
            gstRecoveryOption: 'None',
            date: '2019-12-23T03:41:11',
            principal: 17.82,
            interest: 3.33,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 7,
            gstRecoveryOption: 'None',
            date: '2019-12-30T03:41:11',
            principal: 17.89,
            interest: 3.26,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 8,
            gstRecoveryOption: 'None',
            date: '2020-01-06T03:41:11',
            principal: 17.95,
            interest: 3.2,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 9,
            gstRecoveryOption: 'None',
            date: '2020-01-13T03:41:11',
            principal: 18.02,
            interest: 3.13,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 10,
            gstRecoveryOption: 'None',
            date: '2020-01-20T03:41:11',
            principal: 18.09,
            interest: 3.06,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 11,
            gstRecoveryOption: 'None',
            date: '2020-01-27T03:41:11',
            principal: 18.15,
            interest: 3,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 12,
            gstRecoveryOption: 'None',
            date: '2020-02-03T03:41:11',
            principal: 18.22,
            interest: 2.93,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 13,
            gstRecoveryOption: 'None',
            date: '2020-02-10T03:41:11',
            principal: 18.28,
            interest: 2.87,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 14,
            gstRecoveryOption: 'None',
            date: '2020-02-17T03:41:11',
            principal: 18.35,
            interest: 2.8,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 15,
            gstRecoveryOption: 'None',
            date: '2020-02-24T03:41:11',
            principal: 18.42,
            interest: 2.73,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 16,
            gstRecoveryOption: 'None',
            date: '2020-03-02T03:41:11',
            principal: 18.49,
            interest: 2.66,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 17,
            gstRecoveryOption: 'None',
            date: '2020-03-09T03:41:11',
            principal: 18.55,
            interest: 2.6,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 18,
            gstRecoveryOption: 'None',
            date: '2020-03-16T03:41:11',
            principal: 18.62,
            interest: 2.53,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 19,
            gstRecoveryOption: 'None',
            date: '2020-03-23T03:41:11',
            principal: 18.69,
            interest: 2.46,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 20,
            gstRecoveryOption: 'None',
            date: '2020-03-30T03:41:11',
            principal: 18.76,
            interest: 2.39,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 21,
            gstRecoveryOption: 'None',
            date: '2020-04-06T03:41:11',
            principal: 18.83,
            interest: 2.32,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 22,
            gstRecoveryOption: 'None',
            date: '2020-04-13T03:41:11',
            principal: 18.89,
            interest: 2.26,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 23,
            gstRecoveryOption: 'None',
            date: '2020-04-20T03:41:11',
            principal: 18.96,
            interest: 2.19,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 24,
            gstRecoveryOption: 'None',
            date: '2020-04-27T03:41:11',
            principal: 19.03,
            interest: 2.12,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 25,
            gstRecoveryOption: 'None',
            date: '2020-05-04T03:41:11',
            principal: 19.1,
            interest: 2.05,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 26,
            gstRecoveryOption: 'None',
            date: '2020-05-11T03:41:11',
            principal: 19.17,
            interest: 1.98,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 27,
            gstRecoveryOption: 'None',
            date: '2020-05-18T03:41:11',
            principal: 19.24,
            interest: 1.91,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 28,
            gstRecoveryOption: 'None',
            date: '2020-05-25T03:41:11',
            principal: 19.31,
            interest: 1.84,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 29,
            gstRecoveryOption: 'None',
            date: '2020-06-01T03:41:11',
            principal: 19.38,
            interest: 1.77,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 30,
            gstRecoveryOption: 'None',
            date: '2020-06-08T03:41:11',
            principal: 19.45,
            interest: 1.7,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 31,
            gstRecoveryOption: 'None',
            date: '2020-06-15T03:41:11',
            principal: 19.52,
            interest: 1.63,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 32,
            gstRecoveryOption: 'None',
            date: '2020-06-22T03:41:11',
            principal: 19.6,
            interest: 1.55,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 33,
            gstRecoveryOption: 'None',
            date: '2020-06-29T03:41:11',
            principal: 19.67,
            interest: 1.48,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 34,
            gstRecoveryOption: 'None',
            date: '2020-07-06T03:41:11',
            principal: 19.74,
            interest: 1.41,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 35,
            gstRecoveryOption: 'None',
            date: '2020-07-13T03:41:11',
            principal: 19.81,
            interest: 1.34,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 36,
            gstRecoveryOption: 'None',
            date: '2020-07-20T03:41:11',
            principal: 19.88,
            interest: 1.27,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 37,
            gstRecoveryOption: 'None',
            date: '2020-07-27T03:41:11',
            principal: 19.96,
            interest: 1.19,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 38,
            gstRecoveryOption: 'None',
            date: '2020-08-03T03:41:11',
            principal: 20.03,
            interest: 1.12,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 39,
            gstRecoveryOption: 'None',
            date: '2020-08-10T03:41:11',
            principal: 20.1,
            interest: 1.05,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 40,
            gstRecoveryOption: 'None',
            date: '2020-08-17T03:41:11',
            principal: 20.18,
            interest: 0.97,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 41,
            gstRecoveryOption: 'None',
            date: '2020-08-24T03:41:11',
            principal: 20.25,
            interest: 0.9,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 42,
            gstRecoveryOption: 'None',
            date: '2020-08-31T03:41:11',
            principal: 20.32,
            interest: 0.83,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 43,
            gstRecoveryOption: 'None',
            date: '2020-09-07T03:41:11',
            principal: 20.4,
            interest: 0.75,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 44,
            gstRecoveryOption: 'None',
            date: '2020-09-14T03:41:11',
            principal: 20.47,
            interest: 0.68,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 45,
            gstRecoveryOption: 'None',
            date: '2020-09-21T03:41:11',
            principal: 20.55,
            interest: 0.6,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 46,
            gstRecoveryOption: 'None',
            date: '2020-09-28T03:41:11',
            principal: 20.62,
            interest: 0.53,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 47,
            gstRecoveryOption: 'None',
            date: '2020-10-05T03:41:11',
            principal: 20.7,
            interest: 0.45,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 48,
            gstRecoveryOption: 'None',
            date: '2020-10-12T03:41:11',
            principal: 20.77,
            interest: 0.38,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 49,
            gstRecoveryOption: 'None',
            date: '2020-10-19T03:41:11',
            principal: 20.85,
            interest: 0.3,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 50,
            gstRecoveryOption: 'None',
            date: '2020-10-26T03:41:11',
            principal: 20.93,
            interest: 0.22,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 51,
            gstRecoveryOption: 'None',
            date: '2020-11-02T03:41:11',
            principal: 21,
            interest: 0.15,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
          {
            seq: 52,
            gstRecoveryOption: 'None',
            date: '2020-11-09T03:41:11',
            principal: 20.84,
            interest: 0.31,
            feeAmount: 0,
            structured: 'N',
            held: 'N',
            externalFeeAmount: 0,
            gstAmount: 0,
            instalmentAmount: 21.15,
          },
        ],
      },
      instalmentSummary: [
        {
          startDate: '2019-11-18T03:41:11',
          endDate: '2020-11-09T03:41:11',
          numberOfInstalments: 52,
          amount: 21.15,
          instalmentType: 'PandI',
        },
      ],
    },
  },
}

export default amortisation
