export const primeAndJointOnlyDataTest = {
  draft: 'N',
  loanAmount: 50000,
  interestRate: 12.5,
  repayAmount: 413.09,
  repayFreq: 'F',
  loanPurpose: 'HOIT',
  term: 84,
  tradingBranch: 'WHK',
  insurance: [
    {
      component: 'DEATH',
      joint: 'N',
      discount: 'N',
    },
    {
      component: 'DISABILITY',
      joint: 'Y',
      discount: 'N',
    },
    {
      component: 'BANKRUPTCY',
      joint: 'N',
      discount: 'Y',
    },
    {
      component: 'BANKRUPTCY',
      joint: 'Y',
      discount: 'Y',
    },
    {
      component: 'CRITICLILL',
      joint: 'N',
      discount: 'Y',
    },
    {
      component: 'CRITICLILL',
      joint: 'Y',
      discount: 'Y',
    },
  ],
  associatedClients: {
    data: [
      {
        id: '0001022184',
        type: 'associatedClients',
      },
      {
        id: '0000000001',
        type: 'associatedClients',
      },
    ],
  },
  securities: {
    data: [
      {
        type: 'securities',
        id: '0000299612',
      },
    ],
  },
  memoLines: ['', '------ Credit Sense ------', '', 'Reference: Vicliph-15122022133713', '', '------ Loan Protection Insurance ------', '', 'Total Premium: $8996.32', '', 'Prime Borrower Covers: Death  , Bankruptcy , Critical Illness', '', 'Co-Borrower Covers:  , Disability , Bankruptcy , Critical Illness', '', '------ Vehicle Details for Security ------', '', 'Vehicle-related Loan Purpose? : No', '', 'Would you like to provide vehicle as loan security? : Yes', '', 'Have you purchased the vehicle yet? : Yes', '', 'Vehicle Rego : FAM958', '', '------ Preliminary Questions ------', '', 'Are you applying for a joint loan? : Yes', '', 'What is the purpose of this loan? : Appliance Purchase', '', 'Trading Branch : Whakatane', '', 'Citizenship? : Norfolk Island', '', 'Residency : Christmas Island', '', 'Do you have a work permit? : Yes', '', 'Do you have a regular income? : Yes', '', 'Is your income credited to your FCU Account?: Yes', '', 'Have you been declared bankrupt before? : Yes', '', 'Bankruptcy Date: 15 May 2010', '', '------ Privacy Declaration -------', '', '1. Accepted Credit Assesment Checks- Yes', '', '2. Authorise FCU to disclose data to third parties - Yes', '', '3. Information is true and correct - Yes', '', '4. Comply with AML/CFT obligations - Yes', '', '5. Authorise FCU to collect, use and store data - Yes'],
  included: [
    {
      type: 'associatedClients',
      id: '0001022184',
      attributes: {
        role: 'PRIMEB',
        seq: '1',
        signatureRequired: 'M',
        creditCheckAuthorised: 'Y',
        order: '1',
        clientReference: null,
        clientMaint: {
          clientID: '0001022184',
          generalDetails: {
            externalSystemReference: '',
            clientType: 'I',
            status: {
              code: 'A',
            },
            gna: 'N',
            existingClient: 'Y',
            defaultManager: '0000148335',
            individualDetails: {
              title: 'Mr',
              forename: 'Isaac',
              surname: 'Vicliph',
              clientOtherNamesExist: 'N',
              gender: 'Male',
              dateOfBirth: '1991-06-21',
              dateOfBirthRefused: 'N',
              maritalStatus: 'S',
              countryOfResidence: 'CX',
              countryOfCitizenship: 'NF',
              numberOfDependants: '3',
              accommodation: {
                code: 'RNT2',
                description: 'Renting less than 2',
              },
              resident: 'N',
              smoker: 'N',
            },
          },
          clientIdentifications: [
            {
              idCode1: 'DRVLSC',
              effectiveDate: '2012-06-21',
              expiryDate: '2022-12-21',
              reference: 'DR789456',
              seq: '1',
            },
            {
              idCode1: 'DRVLSC',
              idCode2: 'DLVERSION',
              effectiveDate: '2012-06-21',
              expiryDate: '2022-12-21',
              reference: '714',
              seq: '1',
            },
            {
              idCode1: 'PASPRT',
              effectiveDate: '2012-06-21',
              expiryDate: '2020-12-21',
              reference: 'XE789456',
              seq: '1',
            },
            {
              idCode1: 'FIRELICENS',
              effectiveDate: '2012-06-21',
              expiryDate: '2022-12-22',
              reference: 'YG54545',
              seq: '1',
            },
            {
              idCode1: 'KIWACCCRD',
              effectiveDate: '2012-06-21',
              expiryDate: '2022-12-21',
              reference: '7487654565',
              seq: '1',
            },
            {
              idCode1: 'COMSERVCRD',
              effectiveDate: '2019-06-21',
              expiryDate: '2022-12-21',
              reference: '45654654',
              seq: '1',
            },
            {
              idCode1: 'BIRTHCERT',
              effectiveDate: '2022-12-16',
              reference: '45654654',
              seq: '1',
            },
            {
              idCode1: 'CURSTUDID',
              effectiveDate: '2012-06-21',
              expiryDate: '2022-12-21',
              reference: '45654654',
              seq: '1',
            },
            {
              idCode1: 'GOLDCARD',
              effectiveDate: '2012-06-21',
              reference: '45654654',
              seq: '1',
            },
          ],
          contactDetails: {
            address: [
              {
                careOfName: '',
                unitType: 'Unit',
                apartment: '2',
                building: null,
                streetNumber: {
                  from: '16',
                  to: null,
                },
                alpha: null,
                streetOrPostalName: 'Manning Street',
                streetDirection: null,
                streetType: null,
                suburb: 'Hamilton Central',
                city: 'Hamilton',
                state: '',
                postCode: '3204',
                country: {
                  code: 'NZD',
                  description: 'New Zealand',
                },
                contactId: '258790',
                purpose: 'R',
                effectiveDate: '2021-12-16',
                type: 'S',
                seq: '1',
                externalSystemReference: '',
              },
              {
                careOfName: '',
                unitType: null,
                apartment: null,
                streetNumber: {
                  from: '63',
                  to: null,
                },
                alpha: null,
                streetOrPostalName: 'Ascot Road',
                streetDirection: null,
                streetType: null,
                suburb: 'Chartwell',
                city: 'Hamilton',
                state: '',
                postCode: '3210',
                country: {
                  code: 'NZD',
                  description: 'New Zealand',
                },
                contactId: '258790',
                purpose: 'R',
                effectiveDate: '2016-09-17',
                type: 'S',
                seq: '1',
                externalSystemReference: '',
              },
            ],
            phone: [
              {
                countryCode: '64',
                stdCode: '7',
                number: '8344819',
                preferredMethod: 'N',
                effectiveDate: '2022-12-16',
                type: 'WK',
                seq: '1',
              },
              {
                countryCode: '64',
                stdCode: '7',
                number: '8344810',
                preferredMethod: 'N',
                effectiveDate: '2022-12-16',
                type: 'HM',
                seq: '1',
              },
            ],
            mobile: [
              {
                countryCode: '64',
                networkCode: '21',
                number: '2549633',
                preferredMethod: 'N',
                effectiveDate: '2022-12-16',
                type: 'MB',
                seq: '1',
              },
            ],
            email: [
              {
                address: 'samisaac75@gmail.com',
                preferredMethod: 'Y',
                effectiveDate: '2022-12-16',
                type: 'HM',
                seq: '1',
              },
            ],
          },
          employmentDetails: [
            {
              employmentType: {
                type: 'FTM',
                description: 'Full-Time Employment',
              },
              occupation: '001',
              jobDescription: 'Managers',
              employerName: 'First Credit Union',
              effectiveDate: '2019-09-16',
              seq: '1',
            },
            {
              employmentType: {
                type: 'FTM',
                description: 'Full-Time Employment',
              },
              occupation: '001',
              jobDescription: 'Managers',
              employerName: 'ASB',
              effectiveDate: '1922-12-15',
              seq: '1',
            },
          ],
          clientCapacity: {
            capacityAssessment: {
              anyExpectedChanges: 'Y',
              changeDetails: 'N',
              assessmentQuestionsAsked: 'Y',
              selfDeclarationAccepted: 'Y',
            },
            joint: 'N',
            assets: [
              {
                amount: 1000,
                description: 'Home',
                code: 'HOME',
              },
              {
                amount: 1000,
                description: 'Household Contents',
                code: 'HSHLDCNT',
              },
              {
                amount: 1000,
                description: 'Motor Vehicle/s',
                code: 'MTRVHCAS',
              },
              {
                amount: 1000,
                description: 'Boat',
                code: 'BOAT',
              },
              {
                amount: 1000,
                description: 'Savings',
                code: 'SAVNG',
              },
              {
                amount: 1000,
                description: 'Kiwisaver/Superannuation',
                code: 'KIWISUPER',
              },
              {
                amount: 1000,
                description: 'New Zealand Super',
                code: 'NZSUPER',
              },
              {
                amount: 1000,
                description: 'Bank Account S6',
                code: 'ACCNTS6',
              },
            ],
            liabilities: [
              {
                amount: 50,
                description: 'First Mortgage',
                code: '1STMORT',
              },
              {
                amount: 50,
                description: 'Store Cards/Hire Purchase',
                code: 'SCRDHPUR',
              },
              {
                amount: 50,
                description: 'Mastercard',
                code: 'MSCARD',
              },
              {
                amount: 50,
                description: 'Visa Card',
                code: 'VISACARD',
              },
              {
                amount: 50,
                description: 'Student Loan',
                code: 'STUDENTLO',
              },
            ],
            incomes: [
              {
                amount1: {
                  value: 5500,
                },
                description: 'Wages',
                code: 'WAGES',
              },
              {
                amount1: {
                  value: 5500,
                },
                description: 'WINZ Benefit',
                code: 'BENFIT',
              },
              {
                amount1: {
                  value: 5500,
                },
                description: 'Superannuation',
                code: 'SUPER',
              },
              {
                amount1: {
                  value: 5500,
                },
                description: 'Rental Income',
                code: 'RENTAL',
              },
              {
                amount1: {
                  value: 5500,
                },
                description: 'Working for Families',
                code: 'WKFAM',
              },
              {
                amount2: {
                  value: 5500,
                },
                description: 'Other Income',
                code: 'OTHIN1',
              },
              {
                amount2: {
                  value: 5500,
                },
                description: 'Child Support',
                code: 'CHDSUP',
              },
              {
                amount2: {
                  value: 5500,
                },
                description: 'Boarder Income',
                code: 'PYGBRD',
              },
              {
                amount3: {
                  value: 5500,
                },
                description: 'Self Employed',
                code: 'SLFEMP',
              },
              {
                amount3: {
                  value: 5500,
                },
                description: 'Study Link',
                code: 'STDYLK',
              },
            ],
            expenses: [
              {
                amount1: {
                  value: 100,
                },
                description: 'Renting or Boarding',
                code: 'RENTI',
              },
              {
                amount1: {
                  value: 100,
                },
                description: 'Power or Gas',
                code: 'POWER',
              },
              {
                amount1: {
                  value: 100,
                },
                description: 'Fuel',
                code: 'FUEL',
              },
              {
                amount1: {
                  value: 100,
                },
                description: 'Clothing',
                code: 'CLOTH',
              },
              {
                amount1: {
                  value: 100,
                },
                description: 'Medical',
                code: 'MEDC',
              },
              {
                amount1: {
                  value: 100,
                },
                description: 'Recreation',
                code: 'RECR',
              },
              {
                amount1: {
                  value: 100,
                },
                description: 'Tithing',
                code: 'TITH',
              },
              {
                amount2: {
                  value: 100,
                },
                description: 'S6/Savings',
                code: 'S6',
              },
              {
                amount2: {
                  value: 100,
                },
                description: 'Groceries',
                code: 'GROCER',
              },
              {
                amount2: {
                  value: 100,
                },
                description: 'Gym',
                code: 'GYM',
              },
              {
                amount2: {
                  value: 100,
                },
                description: 'Savings',
                code: 'SAVG',
              },
              {
                amount3: {
                  value: 100,
                },
                description: 'Vehicle on road costs',
                code: 'VEH',
              },
            ],
          },
          mode: 'Add',
        },
      },
    },
    {
      type: 'associatedClients',
      id: '0000000001',
      attributes: {
        role: 'CO-BOR',
        seq: '2',
        signatureRequired: 'O',
        creditCheckAuthorised: 'Y',
        order: '2',
        clientReference: null,
        clientMaint: {
          clientID: '0000000001',
          generalDetails: {
            externalSystemReference: '',
            clientType: 'I',
            status: {
              code: 'A',
            },
            gna: 'N',
            existingClient: 'Y',
            defaultManager: '0000148335',
            individualDetails: {
              title: 'Mr',
              forename: 'John',
              surname: 'Doe',
              clientOtherNamesExist: 'N',
              gender: 'Male',
              dateOfBirth: '1985-11-10',
              dateOfBirthRefused: 'N',
              maritalStatus: 'S',
              countryOfResidence: 'NZD',
              countryOfCitizenship: 'NZD',
              numberOfDependants: '1',
              accommodation: {
                code: 'RNT2',
                description: 'Renting less than 2',
              },
              resident: 'Y',
              smoker: 'N',
            },
          },
          clientIdentifications: [
            {
              idCode1: 'DRVLSC',
              effectiveDate: '2019-06-21',
              expiryDate: '2029-06-21',
              reference: 'JY789456',
              seq: '1',
            },
            {
              idCode1: 'DRVLSC',
              idCode2: 'DLVERSION',
              effectiveDate: '2019-06-21',
              expiryDate: '2029-06-21',
              reference: '714',
              seq: '1',
            },
            {
              idCode1: 'PASPRT',
              effectiveDate: '2019-06-21',
              expiryDate: '2029-06-21',
              reference: 'DT789894',
              seq: '1',
            },
            {
              idCode1: 'FIRELICENS',
              effectiveDate: '2019-06-21',
              expiryDate: '2029-06-21',
              reference: '468654654',
              seq: '1',
            },
            {
              idCode1: 'KIWACCCRD',
              effectiveDate: '2019-06-21',
              expiryDate: '2029-06-21',
              reference: '468654654',
              seq: '1',
            },
            {
              idCode1: 'COMSERVCRD',
              effectiveDate: '2019-06-21',
              expiryDate: '2022-06-21',
              reference: '468654654',
              seq: '1',
            },
            {
              idCode1: 'BIRTHCERT',
              effectiveDate: '2022-12-16',
              reference: '468654654',
              seq: '1',
            },
            {
              idCode1: 'CURSTUDID',
              effectiveDate: '2019-06-21',
              expiryDate: '2029-06-21',
              reference: '468654654',
              seq: '1',
            },
            {
              idCode1: 'GOLDCARD',
              effectiveDate: '2019-06-21',
              reference: '468654654',
              seq: '1',
            },
          ],
          contactDetails: {
            address: [
              {
                careOfName: '',
                unitType: null,
                apartment: null,
                building: null,
                streetNumber: {
                  from: '28',
                  to: null,
                },
                alpha: null,
                streetOrPostalName: 'Pearson Street',
                streetDirection: null,
                streetType: null,
                suburb: 'Mangawhai',
                city: 'Mangawhai',
                state: '',
                postCode: '0505',
                country: {
                  code: 'NZD',
                  description: 'New Zealand',
                },
                contactId: '258790',
                purpose: 'R',
                effectiveDate: '2021-12-16',
                type: 'S',
                seq: '1',
                externalSystemReference: '',
              },
              {
                careOfName: '',
                unitType: null,
                apartment: null,
                building: null,
                streetNumber: {
                  from: '34',
                  to: null,
                },
                alpha: null,
                streetOrPostalName: 'Finlays Road',
                streetDirection: null,
                streetType: null,
                suburb: 'Windsor',
                city: 'Windsor',
                state: '',
                postCode: '9491',
                country: {
                  code: 'NZD',
                  description: 'New Zealand',
                },
                contactId: '258790',
                purpose: 'R',
                effectiveDate: '2017-11-17',
                type: 'S',
                seq: '1',
                externalSystemReference: '',
              },
            ],
            phone: [
              {
                countryCode: '64',
                stdCode: '7',
                number: '8344819',
                preferredMethod: 'N',
                effectiveDate: '2022-12-16',
                type: 'WK',
                seq: '1',
              },
              {
                countryCode: '64',
                stdCode: '7',
                number: '8344810',
                preferredMethod: 'N',
                effectiveDate: '2022-12-16',
                type: 'HM',
                seq: '1',
              },
            ],
            mobile: [
              {
                countryCode: '64',
                networkCode: '21',
                number: '2549633',
                preferredMethod: 'N',
                effectiveDate: '2022-12-16',
                type: 'MB',
                seq: '1',
              },
            ],
            email: [
              {
                address: 'johndoe@gmail.com',
                preferredMethod: 'Y',
                effectiveDate: '2022-12-16',
                type: 'HM',
                seq: '1',
              },
            ],
          },
          employmentDetails: [
            {
              employmentType: {
                type: 'FTM',
                description: 'Full-Time Employment',
              },
              occupation: '001',
              jobDescription: 'Managers',
              employerName: 'BNZ',
              effectiveDate: '2019-09-16',
              seq: '1',
            },
            {
              employmentType: {
                type: 'FTM',
                description: 'Full-Time Employment',
              },
              occupation: '001',
              jobDescription: 'Managers',
              employerName: 'KFC',
              effectiveDate: '1922-12-15',
              seq: '1',
            },
          ],
          mode: 'Add',
        },
      },
    },
    {
      type: 'securities',
      id: '0000299612',
      attributes: {
        seq: '1',
        accountSecurity: {
          primaryCollateral: 'P',
          effectiveDate: '2022-12-16',
          clientSecurityRelationship: 'O',
        },
        asset: {
          assetType: 'S',
          classificationCode: 'VEHI',
          securityPercentageToUse: '100',
          condition: {
            code: 'U',
            description: '',
          },
          securityStatus: {
            code: 'C',
            description: '',
          },
        },
        vehicleMaint: {
          assetExtras: [],
          vehicle: {
            value: '0000000000',
            refType: 'ASSIGN',
          },
          vehicleDetails: {
            externalSystemReference: '',
            make: '',
            model: '',
            registrationYear: '',
            colour: '',
            nonStandardVehicle: {
              code: 'Y',
              description: '',
            },
            registrationNumber: 'FAM958',
            odometer: '0',
          },
        },
      },
    },
  ],
}

export const primeOnlyData = {
  draft: 'N',
  loanAmount: 3000,
  interestRate: 12.5,
  repayAmount: 23.55,
  repayFreq: 'W',
  loanPurpose: 'TRVL',
  term: 36,
  tradingBranch: 'VIR',
  insurance: [
    {
      component: 'DEATH',
      joint: 'N',
      discount: 'N',
    },
  ],
  associatedClients: {
    data: [
      {
        id: '0001022184',
        type: 'associatedClients',
      },
    ],
  },
  securities: {
    data: [
      {
        type: 'securities',
        id: '0000299612',
      },
    ],
  },
  memoLines: ['', '------ Credit Sense ------', '', 'Reference: Vicliph-15122022084113', '', '------ Loan Protection Insurance ------', '', 'Total Premium: $30.61', '', 'Prime Borrower Covers: Death   ', '', 'Co-Borrower Covers:    ', '', '------ Vehicle Details for Security ------', '', 'Vehicle-related Loan Purpose? : No', '', 'Would you like to provide vehicle as loan security? : No', '', 'Have you purchased the vehicle yet? : false', '', 'Vehicle Rego : ', '', '------ Preliminary Questions ------', '', 'Are you applying for a joint loan? : No', '', 'What is the purpose of this loan? : Travel & Vacation Costs', '', 'Trading Branch : Virtual', '', 'Citizenship? : New Zealand', '', 'Residency : N/A', '', 'Do you have a work permit? : N/A', '', 'Do you have a regular income? : Yes', '', 'Is your income credited to your FCU Account?: Yes', '', 'Have you been declared bankrupt before? : No', '', 'Bankruptcy Date: N/A', '', '------ Privacy Declaration -------', '', '1. Accepted Credit Assesment Checks- Yes', '', '2. Authorise FCU to disclose data to third parties - Yes', '', '3. Information is true and correct - Yes', '', '4. Comply with AML/CFT obligations - Yes', '', '5. Authorise FCU to collect, use and store data - Yes'],
  included: [
    {
      type: 'associatedClients',
      id: '0001022184',
      attributes: {
        role: 'PRIMEB',
        seq: '1',
        signatureRequired: 'M',
        creditCheckAuthorised: 'Y',
        order: '1',
        clientReference: null,
        clientMaint: {
          clientID: '0001022184',
          generalDetails: {
            externalSystemReference: '',
            clientType: 'I',
            status: {
              code: 'A',
            },
            gna: 'N',
            existingClient: 'Y',
            defaultManager: '0000148335',
            individualDetails: {
              title: 'Mr',
              forename: 'Isaac',
              surname: 'Vicliph',
              clientOtherNamesExist: 'N',
              gender: 'Male',
              dateOfBirth: '1991-06-21',
              dateOfBirthRefused: 'N',
              maritalStatus: 'S',
              countryOfResidence: null,
              countryOfCitizenship: 'NZ',
              numberOfDependants: '2',
              accommodation: {
                code: 'RNTX',
                description: 'Renting More than 2 years',
              },
              resident: 'Y',
              smoker: 'N',
            },
          },
          clientIdentifications: [
            {
              idCode1: 'PASPRT',
              effectiveDate: '2012-06-21',
              expiryDate: '2022-12-21',
              reference: 'XE123456',
              seq: '1',
            },
          ],
          contactDetails: {
            address: [
              {
                careOfName: '',
                unitType: 'Unit',
                apartment: '2',
                building: null,
                streetNumber: {
                  from: '16',
                  to: null,
                },
                alpha: null,
                streetOrPostalName: 'Manning Street',
                streetDirection: null,
                streetType: null,
                suburb: 'Hamilton Central',
                city: 'Hamilton',
                state: '',
                postCode: '3204',
                country: {
                  code: 'NZD',
                  description: 'New Zealand',
                },
                contactId: '258790',
                purpose: 'R',
                effectiveDate: '2019-12-15',
                type: 'S',
                seq: '1',
                externalSystemReference: '',
              },
            ],
            phone: [],
            mobile: [
              {
                countryCode: '64',
                networkCode: '21',
                number: '2549633',
                preferredMethod: 'N',
                effectiveDate: '2022-12-15',
                type: 'MB',
                seq: '1',
              },
            ],
            email: [
              {
                address: 'samisaac75@gmail.com',
                preferredMethod: 'Y',
                effectiveDate: '2022-12-15',
                type: 'HM',
                seq: '1',
              },
            ],
          },
          employmentDetails: [
            {
              employmentType: {
                type: 'FTM',
                description: 'Full-Time Employment',
              },
              occupation: '001',
              jobDescription: 'Managers',
              employerName: 'FCU',
              effectiveDate: '2020-12-15',
              seq: '1',
            },
          ],
          clientCapacity: {
            capacityAssessment: {
              anyExpectedChanges: 'Y',
              changeDetails: 'N',
              assessmentQuestionsAsked: 'Y',
              selfDeclarationAccepted: 'Y',
            },
            joint: 'N',
            assets: [],
            liabilities: [],
            incomes: [],
            expenses: [],
          },
          mode: 'Add',
        },
      },
    },
    {
      type: 'securities',
      id: '0000299612',
      attributes: {
        seq: '1',
        accountSecurity: {
          primaryCollateral: 'P',
          effectiveDate: '2022-12-15',
          clientSecurityRelationship: 'O',
        },
        asset: {
          assetType: 'S',
          classificationCode: 'VEHI',
          securityPercentageToUse: '100',
          condition: {
            code: 'U',
            description: '',
          },
          securityStatus: {
            code: 'C',
            description: '',
          },
        },
        vehicleMaint: {
          assetExtras: [],
          vehicle: {
            value: '0000000000',
            refType: 'ASSIGN',
          },
          vehicleDetails: {
            externalSystemReference: '',
            make: '',
            model: '',
            registrationYear: '',
            colour: '',
            nonStandardVehicle: {
              code: 'Y',
              description: '',
            },
            registrationNumber: '',
            odometer: '0',
          },
        },
      },
    },
  ],
}

export const primeAndJointPDFData = {
  applicationData: {
    creditSense: {
      reference: 'Vicliph-15122022135847',
    },
    loanProtectionInsurance: {
      totalPremium: 8196.39,
      prime: {
        death: true,
        disability: true,
        bankrptcy: true,
        criticalIllness: false,
      },
      coborrower: {
        death: false,
        disability: true,
        bankrptcy: true,
        criticalIllness: true,
      },
    },
    securityDetails: {
      vehicle: {
        registrationNumber: 'FAM958',
        vehicleRelatedLoanPurpose: 'No',
        wouldYouLikeToProvideVehicleAsSecurity: 'Yes',
        haveYouPurchasedTheVehicle: 'Yes',
      },
    },
    primeDetails: {
      applicationNumber: '0020824033',
      individualDetails: {
        title: 'Mr',
        forename: 'Isaac',
        surname: 'Vicliph',
        clientOtherNamesExist: 'N',
        gender: 'Male',
        dateOfBirth: '21 June 1991',
        dateOfBirthRefused: 'N',
        maritalStatus: 'Single',
        countryOfResidence: 'CX',
        countryOfCitizenship: 'GE',
        numberOfDependants: '2',
        accommodationDesc: 'Renting less than 2',
        resident: 'N',
        smoker: 'N',
      },
      identification: {
        drLicence: {
          isPresent: 'DRVLSC',
          reference: 'DT789456',
          driversLicenceVersion: '714',
          driversLicenceType: 'Full',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        passport: {
          isPresent: 'PASPRT',
          reference: 'SE789456',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        firearmsLicence: {
          isPresent: 'FIRELICENS',
          reference: 'S5645445E',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        kiwiAccessCard: {
          isPresent: 'KIWACCCRD',
          reference: '465465465',
          issueDate: '2019-06-21',
          expiryDate: '2022-06-21',
        },
        communityServiceCard: {
          isPresent: 'COMSERVCRD',
          reference: '465465465',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        birthCertificate: {
          isPresent: 'BIRTHCERT',
          reference: '748435465',
          issueDate: '15 December 2022',
        },
        currentStudentId: {
          isPresent: 'CURSTUDID',
          reference: '4654654',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        goldCard: {
          isPresent: 'GOLDCARD',
          reference: '54656880',
          issueDate: '21 June 2019',
        },
      },
      address: {
        primeCurrentResidence: {
          addressLine1: '63 Ascot Road',
          addressLine2: 'Mount Maunganui 3116',
          addressLine3: null,
          addressLine4: null,
        },
        primePreviousResidence: {
          addressLine1: 'Unit 2',
          addressLine2: '16 Manning Street',
          addressLine3: 'Hamilton Central',
          addressLine4: 'Hamilton 3204',
        },
      },
      phone: [
        {
          countryCode: '64',
          stdCode: '7',
          number: '8344819',
          preferredMethod: 'N',
          effectiveDate: '2022-12-16',
          type: 'WK',
          seq: '1',
        },
        {
          countryCode: '64',
          stdCode: '7',
          number: '8344810',
          preferredMethod: 'N',
          effectiveDate: '2022-12-16',
          type: 'HM',
          seq: '1',
        },
      ],
      mobile: [
        {
          countryCode: '64',
          networkCode: '21',
          number: '2549633',
          preferredMethod: 'N',
          effectiveDate: '2022-12-16',
          type: 'MB',
          seq: '1',
        },
      ],
      email: [
        {
          address: 'samisaac75@gmail.com',
          preferredMethod: 'Y',
          effectiveDate: '2022-12-16',
          type: 'HM',
          seq: '1',
        },
      ],
      employemnt: {
        primeCurrentEmployment: {
          employmentType: 'Full-Time Employment',
          occupation: 'Managers',
          jobDescription: 'Managers',
          employerName: 'First Credit Union',
          effectiveDate: '15 December 2018',
          addressLine1: '11 Abercromby Street',
          addressLine2: 'Porangahau 4291',
          addressLine3: null,
          addressLine4: null,
        },
        primePreviousEmployment: {
          employmentType: 'Full-Time Employment',
          occupation: 'Managers',
          jobDescription: 'Managers',
          employerName: 'Bank of New Zealand',
          effectiveDate: '15 December 1922',
          addressLine1: '55 Frederick Street',
          addressLine2: 'Carterton 5713',
          addressLine3: null,
          addressLine4: null,
        },
        jointCurrentEmployment: {
          employmentType: 'Full-Time Employment',
          occupation: '001',
          jobDescription: 'Managers',
          employerName: 'ASB',
          effectiveDate: '15 December 2018',
          addressLine1: '78 Aotaki Street',
          addressLine2: 'Otaki 5512',
          addressLine3: null,
          addressLine4: null,
        },
        jointPreviousEmployment: {
          employmentType: 'Full-Time Employment',
          occupation: '001',
          jobDescription: 'Managers',
          employerName: 'First Credit Union',
          effectiveDate: '15 December 2018',
          addressLine1: '111 Clovelly Road',
          addressLine2: 'Bucklands Beach',
          addressLine3: 'Auckland 2012',
          addressLine4: null,
        },
      },
      assets: [
        {
          amount: 1000,
          description: 'Home',
          code: 'HOME',
        },
        {
          amount: 1000,
          description: 'Household Contents',
          code: 'HSHLDCNT',
        },
        {
          amount: 1000,
          description: 'Motor Vehicle/s',
          code: 'MTRVHCAS',
        },
        {
          amount: 1000,
          description: 'Boat',
          code: 'BOAT',
        },
        {
          amount: 1000,
          description: 'Savings',
          code: 'SAVNG',
        },
        {
          amount: 1000,
          description: 'Kiwisaver/Superannuation',
          code: 'KIWISUPER',
        },
        {
          amount: 1000,
          description: 'New Zealand Super',
          code: 'NZSUPER',
        },
        {
          amount: 1000,
          description: 'Bank Account S6',
          code: 'ACCNTS6',
        },
      ],
      liabilities: [
        {
          amount: 50,
          description: 'First Mortgage',
          code: '1STMORT',
        },
        {
          amount: 50,
          description: 'Store Cards/Hire Purchase',
          code: 'SCRDHPUR',
        },
        {
          amount: 50,
          description: 'Mastercard',
          code: 'MSCARD',
        },
        {
          amount: 50,
          description: 'Visa Card',
          code: 'VISACARD',
        },
        {
          amount: 50,
          description: 'Student Loan',
          code: 'STUDENTLO',
        },
      ],
      incomes: [
        {
          amount: 5000,
          code: 'WAGES',
          description: 'Wages',
          frequency: 'W',
        },
        {
          amount: 5000,
          code: 'OTHIN1',
          description: 'Other Income',
          frequency: 'F',
        },
        {
          amount: 5000,
          code: 'BENFIT',
          description: 'WINZ Benefit',
          frequency: 'W',
        },
        {
          amount: 5000,
          code: 'SLFEMP',
          description: 'Self Employed',
          frequency: 'W',
        },
        {
          amount: 5000,
          code: 'SUPER',
          description: 'Superannuation',
          frequency: 'W',
        },
        {
          amount: 5000,
          code: 'STDYLK',
          description: 'Study Link',
          frequency: 'W',
        },
        {
          amount: 5000,
          code: 'RENTAL',
          description: 'Rental Income',
          frequency: 'M',
        },
        {
          amount: 5000,
          code: 'CHDSUP',
          description: 'Child Support',
          frequency: 'W',
        },
        {
          amount: 5000,
          code: 'WKFAM',
          description: 'Working for Families',
          frequency: 'F',
        },
        {
          amount: 5000,
          code: 'PYGBRD',
          description: 'Boarder Income',
          frequency: 'W',
        },
      ],
      expenses: [
        {
          amount: 250,
          code: 'RENTI',
          description: 'Renting or Boarding',
          frequency: 'W',
        },
        {
          amount: 250,
          code: 'S6',
          description: 'S6/Savings',
          frequency: 'W',
        },
        {
          amount: 250,
          code: 'GROCER',
          description: 'Groceries',
          frequency: 'W',
        },
        {
          amount: 250,
          code: 'POWER',
          description: 'Power or Gas',
          frequency: 'W',
        },
        {
          amount: 250,
          code: 'PHONE',
          description: 'Phone or Internet',
          frequency: 'F',
        },
        {
          amount: 250,
          code: 'FUEL',
          description: 'Fuel',
          frequency: 'W',
        },
        {
          amount: 250,
          code: 'VEH',
          description: 'Vehicle on road costs',
          frequency: 'F',
        },
        {
          amount: 250,
          code: 'CLOTH',
          description: 'Clothing',
          frequency: 'W',
        },
        {
          amount: 250,
          code: 'MEDC',
          description: 'Medical',
          frequency: 'W',
        },
        {
          amount: 250,
          code: 'GYM',
          description: 'Gym',
          frequency: 'M',
        },
        {
          amount: 250,
          code: 'RECR',
          description: 'Recreation',
          frequency: 'W',
        },
        {
          amount: 250,
          code: 'TITH',
          description: 'Tithing',
          frequency: 'W',
        },
        {
          amount: 250,
          code: 'SAVG',
          description: 'Savings',
          frequency: 'M',
        },
      ],
    },
    jointDetails: {
      applicationNumber: '0020824033',
      individualDetails: {
        title: 'Mr',
        forename: 'John',
        surname: 'Doe',
        clientOtherNamesExist: 'N',
        gender: 'Male',
        dateOfBirth: '18 October 1985',
        dateOfBirthRefused: 'N',
        maritalStatus: 'Single',
        countryOfResidence: 'NZD',
        countryOfCitizenship: 'NZD',
        numberOfDependants: '3',
        accommodationDesc: 'Renting less than 2',
      },
      identification: {
        drLicence: {
          isPresent: 'DRVLSC',
          reference: 'GT456896',
          driversLicenceVersion: '714',
          driversLicenceType: 'Full',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        passport: {
          isPresent: 'PASPRT',
          reference: 'WQ789456',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        firearmsLicence: {
          isPresent: 'FIRELICENS',
          reference: '68765465',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        kiwiAccessCard: {
          isPresent: 'KIWACCCRD',
          reference: '68765465',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        communityServiceCard: {
          isPresent: 'COMSERVCRD',
          reference: '68765465',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        birthCertificate: {
          isPresent: 'BIRTHCERT',
          reference: '68765465',
          issueDate: '15 December 2022',
        },
        currentStudentId: {
          isPresent: 'CURSTUDID',
          reference: '68765465',
          issueDate: '21 June 2019',
          expiryDate: '21 June 2022',
        },
        goldCard: {
          isPresent: 'GOLDCARD',
          reference: '68765465',
          issueDate: '21 June 2019',
        },
      },
      address: {
        jointCurrentResidence: {
          addressLine1: '28 Pembroke Crescent',
          addressLine2: 'Glendowie',
          addressLine3: 'Auckland 1071',
          addressLine4: null,
        },
        jointPreviousResidence: {
          addressLine1: '1A Winstone Avenue',
          addressLine2: 'Hamilton 3210',
          addressLine3: null,
          addressLine4: 'Hamilton 3210',
        },
      },
      phone: [
        {
          countryCode: '64',
          stdCode: '7',
          number: '8344819',
          preferredMethod: 'N',
          effectiveDate: '2022-12-16',
          type: 'WK',
          seq: '1',
        },
        {
          countryCode: '64',
          stdCode: '7',
          number: '8344810',
          preferredMethod: 'N',
          effectiveDate: '2022-12-16',
          type: 'HM',
          seq: '1',
        },
      ],
      mobile: [
        {
          countryCode: '64',
          networkCode: '21',
          number: '2549633',
          preferredMethod: 'N',
          effectiveDate: '2022-12-16',
          type: 'MB',
          seq: '1',
        },
      ],
      email: [
        {
          address: 'johndoe@gmail.com',
          preferredMethod: 'Y',
          effectiveDate: '2022-12-16',
          type: 'HM',
          seq: '1',
        },
      ],
      employemnt: {
        primeCurrentEmployment: {
          employmentType: 'Full-Time Employment',
          occupation: 'Managers',
          jobDescription: 'Managers',
          employerName: 'First Credit Union',
          effectiveDate: '15 December 2018',
          addressLine1: '11 Abercromby Street',
          addressLine2: 'Porangahau 4291',
          addressLine3: null,
          addressLine4: null,
        },
        primePreviousEmployment: {
          employmentType: 'Full-Time Employment',
          occupation: 'Managers',
          jobDescription: 'Managers',
          employerName: 'Bank of New Zealand',
          effectiveDate: '15 December 1922',
          addressLine1: '55 Frederick Street',
          addressLine2: 'Carterton 5713',
          addressLine3: null,
          addressLine4: null,
        },
        jointCurrentEmployment: {
          employmentType: 'Full-Time Employment',
          occupation: '001',
          jobDescription: 'Managers',
          employerName: 'ASB',
          effectiveDate: '15 December 2018',
          addressLine1: '78 Aotaki Street',
          addressLine2: 'Otaki 5512',
          addressLine3: null,
          addressLine4: null,
        },
        jointPreviousEmployment: {
          employmentType: 'Full-Time Employment',
          occupation: '001',
          jobDescription: 'Managers',
          employerName: 'First Credit Union',
          effectiveDate: '15 December 2018',
          addressLine1: '111 Clovelly Road',
          addressLine2: 'Bucklands Beach',
          addressLine3: 'Auckland 2012',
          addressLine4: null,
        },
      },
    },
    financialDetails: {
      loanAmount: 30000,
      interestRate: 12.5,
      repayAmount: 123.67,
      repayFreq: 'W',
      term: 84,
    },
    preliminaryQuestions: {
      loanPurpose: 'Travel & Vacation Costs',
      tradingBranch: 'Whakatane',
      citizen: 'GE',
      isNzCitizen: false,
      resident: 'CX',
      isNzResident: false,
      hasWorkPermit: {
        key: 'Yes',
        value: true,
      },
      hasRegularIncome: {
        key: 'Yes',
        value: true,
      },
      incomeCreditedToFCU: {
        key: 'Yes',
        value: true,
      },
      wasDeclaredBankrupt: {
        key: 'Yes',
        value: true,
      },
      bankruptcyDate: '2010-04-30T12:00:00.000Z',
    },
    privacyDeclaration: {
      acceptCreditAssesment: true,
      acceptAuthoriseFCUToUseData: true,
      acceptTrueInformation: true,
      acceptAMLCFTObligations: true,
      acceptStorePersonalInfo: true,
    },
  },
  applicationNumber: '0020824033 - 15122022135907',
}

