import Autocomplete from './AutoComplete'
import Backdrop from './Backdrop'
import Button from './Button'
import ButtonGroup from './ButtonGroup'
import Card from './Card'
import Checkbox from './Checkbox'
import Container from './Container'
import ControlLabel from './ControlLabel'
import CssBaseline from './CssBaseline'
import DataGrid from './DataGrid'
import Dialog from './Dialog'
import Drawer from './Drawer'
import Grid from './Grid'
import IconButton from './IconButton'
import Input from './Input'
import Link from './Link'
import Lists from './List'
import LoadingButton from './LoadingButton'
import Menu from './Menu'
import Paper from './Paper'
import Progress from './Progress'
import Radio from './Radio'
import Select from './Select'
import Slider from './Slider'
import Snackbar from './Snackbar'
import Stepper from './Stepper'
import SvgIcon from './SvgIcon'
import Switch from './Switch'
import Table from './Table'
import ToggleButton from './ToggleButton'
import Tooltip from './Tooltip'
import Typography from './Typography'

export default function ComponentsOverrides(theme) {
  return Object.assign(Autocomplete(theme), Backdrop(theme), Button(theme), ButtonGroup(theme), Card(theme), Checkbox(theme), Container(theme), ControlLabel(theme), CssBaseline(theme), DataGrid(theme), Dialog(theme), Drawer(theme), Grid(theme), IconButton(theme), Input(theme), Link(theme), Lists(theme), LoadingButton(theme), Menu(theme), Paper(theme), Progress(theme), Radio(theme), Select(theme), Slider(theme), Snackbar(theme), Stepper(theme), SvgIcon(theme), Switch(theme), Table(theme), ToggleButton(theme), Tooltip(theme), Typography(theme))
}
